### ISSUE TITLE
Low carbon computation and unknown source

### ISSUE THREAD

**Issue by phiphou** [electricitymaps/electricitymaps-contrib#7097]
Let's take an example, from EM datas : 

Sweden, july 2024 :

- production : 16.8TWh

detail : 

- hydro : 6.64TWh
- wind : 4.77TWh
- nuclear : 4.61TWh
- unknown : 816GWh

Low carbon : 100%

But if I take hydro + wind + nuclear, it gives 16.02TWh, wich is 95.36% of 16.8TWh.

I say myself you're computing the low carbon not from the total production (16.8TWh) but from this quantity minus unknown. So 16.02 is about 100% of 15.98 (16.8-0.816).

But you says unknown has an 258gCO2/kWh emission factor, wich is not low carbon.

I conclude you're not taking in account unknown in low carbon computation. But is that "fair" ?

**Comment by VIKTORVAV99** [comment]
We have low carbon overrides for unknown in some zones.

For Sweden this is currently:
```yaml annotation
    - _comment: Sum of renewable sources in SE unknown production for 2022
      datetime: '2022-01-01'
      value: 0.9826
```
This value is based on the yearly share of reported production in https://ec.europa.eu/eurostat/documents/38154/4956218/Energy-Balances-January-2022-edition.zip/2dc71f1b-806a-b9ed-e77d-67b7c705197b?t=1643660477829

In consumption mode we also take exchanges into account.
